export const TYPES = {
  // ? Repositories
  UsersRepository: Symbol.for('UsersRepository'),
  AuthRepository: Symbol.for('AuthRepository'),
  MoviesRepository: Symbol.for('MoviesRepository'),
  UserRepository: Symbol.for('UserRepository'),
  ActorsRepository: Symbol.for('ActorsRepository'),

  // ? Use Cases
  GetAllUsersUseCase: Symbol.for('GetAllUsersUseCase'),
  RegisterUserUseCase: Symbol.for('RegisterUserUseCase'),
  SigninUserUseCase: Symbol.for('SigninUserUseCase'),
  ResetPasswordUseCase: Symbol.for('ResetPasswordUseCase'),
  RefreshTokenUseCase: Symbol.for('RefreshTokenUseCase'),
  GetMovieDetailsUseCase: Symbol.for('GetMovieDetailsUseCase'),
  GetNowPlayingMoviesUseCase: Symbol.for('GetNowPlayingMoviesUseCase'),
  GetUpcomingMoviesUseCase: Symbol.for('GetUpcomingMoviesUseCase'),
  GetPopularMoviesUseCase: Symbol.for('GetPopularMoviesUseCase'),
  GetTopRatedMoviesUseCase: Symbol.for('GetTopRatedMoviesUseCase'),
  SearchMoviesAndActorsUseCase: Symbol.for('SearchMoviesAndActorsUseCase'),
  GetMoviesByActorUseCase: Symbol.for('GetMoviesByActorUseCase'),
  AddToWatchlistUseCase: Symbol.for('AddToWatchlistUseCase'),
  RemoveFromWatchlistUseCase: Symbol.for('RemoveFromWatchlistUseCase'),
  MarkAsSeenUseCase: Symbol.for('MarkAsSeenUseCase'),
  RemoveSeenMediaUseCase: Symbol.for('RemoveSeenMediaUseCase'),
  RateMediaUseCase: Symbol.for('RateMediaUseCase'),
  UpdateRatingMediaUseCase: Symbol.for('UpdateRatingMediaUseCase'),
  RemoveMediaRatingUseCase: Symbol.for('RemoveMediaRatingUseCase'),
  GetUserSettingsUseCase: Symbol.for('GetUserSettingsUseCase'),
  UpdateUserSettingUseCase: Symbol.for('UpdateUserSettingUseCase'),
  GetUserWatchListUseCase: Symbol.for('GetUserWatchListUseCase'),
  GetUserSeenMediaUseCase: Symbol.for('GetUserSeenMediaUseCase'),
  GetMovieTrailerUseCase: Symbol.for('GetMovieTrailerUseCase'),

  // ? Controllers
  UsersController: Symbol.for('UsersController'),
  AuthController: Symbol.for('AuthController'),
  MoviesController: Symbol.for('MoviesController'),
  SearchController: Symbol.for('SearchController'),
  UserController: Symbol.for('UserController'),
  ActorsController: Symbol.for('ActorsController'),
};
